<a href="https://colab.research.google.com/github/descandon88/lyric-sentiment-analysis/blob/main/Eigenvectors_and_Eigenvalues.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

**Eigenvectors and Eigenvalues**

An **eigenvector** is a special vector *v* such that when it is transformed by some matrix (let's say *A*), the product Av has the exact same direction as *v*.

An **eigenvalue** is a scalar (tradicional represented as λ) that simply scales the eigenvector v such that the following equation is satisfied: 

*A*𝓥 = 𝝀𝓥



In [3]:
A = ([-1,4],[2,-2])
A

([-1, 4], [2, -2])

**Eigenvector** and **eigenvalues** can be derived algebraically (e.g., with QR algorithm, which was independently developed in the 1950s by both Vera Kublanovskaya and John Francis), however this is outside scope of today's class. We-ll cheat with numpy eig()

In [4]:
lambdas, V = np.linalg.eig(A)

The matrix contains as many eigenvectors as there are columns of A: 

In [5]:
V # cada columna es un eigenvector v separado

array([[ 0.86011126, -0.76454754],
       [ 0.51010647,  0.64456735]])

With a corresponding eigenvalue for each eigenvector:

In [6]:
lambdas

array([ 1.37228132, -4.37228132])

Let's confirm that  *A*𝓥 = 𝝀𝓥 for the  first eigenvector:


In [8]:
v = V[:,0]
v

array([0.86011126, 0.51010647])

In [9]:
lambduh = lambdas[0] # note that lambda is reserved term in Python 
lambduh

1.3722813232690143